name       : haskell-src-meta
version    : 0.8.5
release    : 2
source     :
    - https://hackage.haskell.org/package/haskell-src-meta-0.8.5/haskell-src-meta-0.8.5.tar.gz : 331271554ba42e4938da1417df1e3192737c3e19dceb9a5484198c71ecb858b3
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parse source to template-haskell abstract syntax.
description: |
    Parse source to template-haskell abstract syntax.
builddeps  :
    - haskell-cabal-install
    - haskell-src-exts-devel
    - haskell-th-orphans-devel
rundeps    :
    - devel:
        - haskell-src-exts-devel
        - haskell-th-orphans-devel
networking : yes
setup      : |
    sed -i "s|< 1.23|< 1.24|g" haskell-src-meta.cabal
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
