name       : haskell-src-meta
version    : 0.8.0.2
release    : 1
source     :
    - http://hackage.haskell.org/package/haskell-src-meta-0.8.0.2/haskell-src-meta-0.8.0.2.tar.gz : 4b7b143b94fcf147b96bb34822c2feeae29daadd3a22796ee36cadd5ca262c8b
license    : BSD-3-Clause
component  : programming.haskell
summary    : Parse source to template-haskell abstract syntax.
description: |
    Parse source to template-haskell abstract syntax.
builddeps  :
    - haskell-cabal-install
    - haskell-src-exts
    - haskell-syb
    - haskell-th-orphans
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
